import os


GEMINI_API_KEY = os.environ["GEMINI_API_KEY"]
QDRANT_HOST = os.environ.get("QDRANT_HOST", "qdrant")
QDRANT_PORT = int(os.environ.get("QDRANT_PORT", "6333"))

MATTERMOST_API_URL = os.environ.get("MATTERMOST_API_URL", "")
MATTERMOST_BOT_TOKEN = os.environ.get("MATTERMOST_BOT_TOKEN", "")
MATTERMOST_INCOMING_WEBHOOK_URL = os.environ.get("MATTERMOST_INCOMING_WEBHOOK_URL", "")
MATTERMOST_OUTGOING_WEBHOOK_TOKEN = os.environ.get("MATTERMOST_OUTGOING_WEBHOOK_TOKEN", "")

QDRANT_COLLECTION = "estimates"
EMBEDDING_MODEL = "text-embedding-004"
EMBEDDING_DIMENSION = 768
LLM_MODEL = "gemini-2.0-flash"
SEARCH_LIMIT = 5
EMBEDDING_BATCH_SIZE = 100
